# Generated by Django 5.2 on 2025-04-24 21:45

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='short_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Only uppercase letters and numbers are allowed.')]),
            preserve_default=False,
        ),
    ]
